### ISSUE TITLE
Error generating gallery

### ISSUE THREAD

**Issue by createchange** [victoriadotdev/acme-gallery#1] opened 2018-12-12 06:27 UTC
Hey there, I see this is a somewhat older project and you like to jump a bit around, but thought this was cool and wanted to give it a try.

**Error Message:**

```
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/jhw/tmp/acme-gallery/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/jhw/tmp/acme-gallery/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/jhw/tmp/acme-gallery/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
```

Happy to provide whatever info might help you find a solution.

**Comment by victoriadotdev** [comment] 2019-03-12 18:06
Hey @createchange ~

This error seems to have been caused by one of the dependencies (gulp) and should be resolved with the latest version. Please let me know if you continue to see it.

Thank you!

**Closed by victoriadotdev** 2019-03-12 18:06 UTC
